// <auto-generated />
namespace FullyProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class edit30 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit30));
        
        string IMigrationMetadata.Id
        {
            get { return "201902271749472_edit30"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
